# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    JSON_STRING="{
      \"Environment\":\"$(Build.BuildId)\",
      \"Service\":\"$(Build.DefinitionName)\",
      \"Version\":\"$(Build.BuildNumber)\",
      \"DeployDate\":\"$(date +'%d/%m/%Y')\",
      \"Publisher\":\"$(Build.RequestedFor)\"
    }"
    NEW_JSON=$(jq --arg id "427fedaf5e16447b92c533d0ec155894" '. += {"Id": $id}' <<< $JSON_STRING)
    echo $NEW_JSON
    echo "${NEW_JSON}" > myownfile.json
    echo $JSON_STRING | jq .
    # curl -v -d '{"Environment":"'"$(Build.BuildId)"'","Service":"'"$(Build.DefinitionName)"'","Version":"'"$(Build.BuildNumber)"'","DeployDate":"'"$(date +'%d/%m/%Y')"'","Publisher":"'"$(Build.RequestedFor)"'"}' -H "Content-Type: application/json" -X POST "https://prod-234.westeurope.logic.azure.com:443/workflows/ba37919e5e0440ccb5df81631d6b8663/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=6T6hb9EZuODtmd-GP9y9BFt3jDg5PIZ8PIuH26Qe43M"
    curl -v -d "@myownfile.json" -H "Content-Type: application/json" -X POST "https://prod-70.westeurope.logic.azure.com:443/workflows/ecce67397d494c08bdb7be45ab41a627/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=h1iG7Ea6DR6mJ8yyljRZBKyUHNQArGxJM6Oxxuj86uM"
  displayName: 'Run a multi-line script'
