# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo $(Environment.Name)
    echo $(Build.DefinitionName)
    echo $(Build.Repository.Name)
    echo $(Build.RequestedFor)
    echo $(Build.RequestedForEmail)
    echo $(Build.SourceBranch)
    echo $(Build.SourceBranchName)
    echo $(Build.BuildId)
    echo $(Build.BuildNumber)
    echo $(date +'%d/%m/%Y')
    JSON_STRING="{
      \"Environment\":\"$(Build.BuildId)\",
      \"Service\":\"$(Build.DefinitionName)\",
      \"Version\":\"$(Build.BuildNumber)\",
      \"DeployDate\":\"$(date +'%d/%m/%Y')\",
      \"Publisher\":\"$(Build.RequestedFor)\"
    }"
    echo "${JSON_STRING}"
    curl -d "$JSON_STRING" -H "Content-Type: application/json" -X POST https://prod-234.westeurope.logic.azure.com:443/workflows/ba37919e5e0440ccb5df81631d6b8663/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=6T6hb9EZuODtmd-GP9y9BFt3jDg5PIZ8PIuH26Qe43M
  displayName: 'Run a multi-line script'
